language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
branches: 
except:
- /^v\d+\.\d+\.\d+$/
env:
  global:
  - secure: lCch1gtdXn2sWLH9ARCXLGXQpY9jDmMXGPPtzklcmn3siMCZWinoLln5Iq0K7KUTLMR5Z6s6n1phZQ3CHSD6w34vhPUIPrqlDxoYVBtYuqx67vYbXUev6PrKWRZi/ubj3oyhlOyGDo6XzkPbpwC2sNYwUbPeCnOm0zBGcKdzB8XOHVccw6WUvb92/OtJ2wiN5WZdiw/83aCtTpDCh4Jvab8tw+miQyYG/AVnz7X2vtb9rExJ6ID6eXmsAObIr++/FjlUb96VomlW5it8tHwSQor7He2shO0Dyob63aJeGNz24lFAL93Emzf5XrUtqJh2wa3JkhK5JlUb1kx8fRUdHl0ktVLc8WW5AM7FrR4xVrTHuwJCXx/wpmWezyqxjjxA/aPJH8g3x5R/4rgrJfK8an4Fj3gZ/jtsO86pBzO6Dj7CjFzN0oGpI8kJVOCfxxQg09Fk0NUaKLqao9N4MBaY4bOtR9b1szb9f2bZw5UR1QMF+2nDjLt8NKZcfqpxu3OlHVpWMrAYAe6CDpza83iEr1NgyeUYvvFS5ji3074nwqjKQoCSWqdc/rxwecj58/djbi9Qs8vaCES3Uazo0h1KDRtwwFE4FOcgzte1MxUUoo+YpMxAVknVDndWBTh0kn3Bbuisw0fVonmvqO3jFJep+kIzSKFeiQbAgOZvJnrKHPI=
