language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
branches: 
except:
- /^v\d+\.\d+\.\d+$/
env:
  global:
  - secure: gOayAWP67quLbh7MPfb5FLte0Nkwhy/zz9T+NzN9pYYzSbuVyAOqc3dYL4DSBNRn8Vfz0FmlJBf73Xnn4CCTNhuQPSt62L4KlHCnDUY5eSNRIAJo16XNgVeH50gu/i4G48qzgTRdHVytMXTDtNDtI08P9BMxuxfT90hxAvnPJcPwQb4R86QtpohsTrP21icKtsh0Ht3a078UELqgSp1JB+WvIgonxYZDIdaG6EGh8X9o2tF/8ZJu56dFzIH6Pgkrf9ksXRT9/X1rPAulGy5r7GssgATugQvkXMTIp/nDxrnq8D8t+x9iW9g3TwOoWa3NC8XUH9DyB94coYHyYr+ohE6PHdIYna0XBHEA9aq/3cIRytzjXRxITUsiOIuRp6f8sOqoqduZw3U//tc5b+UgFPRPGMeQW0sLVqtONeFuIgUBKfV4COHLVL2Q0C9FlC8JMswBKn3zg4acUfCgE2ydRXbk9XBXfm4RLcyNasFVdlHQL46TEGtXTh8Pw9eyDBHFc7tSMof3J+VlDhtBpn/rTbgC+RrHDJ+9M+yfzAEE778EYd6aLGwXRp0hTXdzr+ud/CGsyBRl4UdHoycnkQ3HXP9RUZtZTcXpfqJZbsf/1tDMMPGal4vzWUqywz4XrHNBtuv6To82ug4HlYcjTsPXdAp3N7g1KDHF7lRATnDpHEE=
  - secure: ez9hL63yq7umGNc+HOdxK8VeQs91LFguBTBydeUVmpU0I8O2D5i3Jy7rgt9FNsP/yvGrnM7+vwVRVtbcPZvBHxG9IeqXLjg/m4C8jiQ+o3hIKdd4GExACbjwCIBUwtdGa5hXLi6hr0VSG5MldJ0apROaHbgytnJFsT04z+jMYWxxy/tXlzS+I1l81Uco5B8T8hgDsyPQZrtiqwKZ/P23zna7W3iJxoDnh5z1/wo9UNwLL7vW9bydRRoxiT6B1+oeacweDVZXMOmdGtsEKbqbczNgVyNVmqoPtgupVXW1DDe9YxjWXYYC1hXyhbooFQBudDeGebsxZqpnQhTXlHyNF4Vp7OxlE6ORH5DJ/3yDPmiuu8mvYQnjmqDPMrp8kusconOlUUDC2YwV4Ny3ClOCdli9Qbvteg1hetX0EVUJtNYod9A3k7XojXeGHJGpFmRlM/6P0Le8X6l6NfbgwQBLXx0+ErvqSkMG+534Ju8L+jJcL86c27/BxJP4zPG83yVSVyxTVHX0CZm9024rpjKDavMeNMHetXepmhMUjxQBe603Bbp3XYn9xOowVjMqsi0yyMZnIfV3F9Pmj+JU7PUloACew28ptC9smXRwn75/i7mrmcl7wkp19nNnGuJfUnfB6X4W6jjG330dljof6hwlkneGRqowYQYd0OzIoSG4baA=
