language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
branches: 
except:
- /^v\d+\.\d+\.\d+$/
env:
  global:
  - secure: gOayAWP67quLbh7MPfb5FLte0Nkwhy/zz9T+NzN9pYYzSbuVyAOqc3dYL4DSBNRn8Vfz0FmlJBf73Xnn4CCTNhuQPSt62L4KlHCnDUY5eSNRIAJo16XNgVeH50gu/i4G48qzgTRdHVytMXTDtNDtI08P9BMxuxfT90hxAvnPJcPwQb4R86QtpohsTrP21icKtsh0Ht3a078UELqgSp1JB+WvIgonxYZDIdaG6EGh8X9o2tF/8ZJu56dFzIH6Pgkrf9ksXRT9/X1rPAulGy5r7GssgATugQvkXMTIp/nDxrnq8D8t+x9iW9g3TwOoWa3NC8XUH9DyB94coYHyYr+ohE6PHdIYna0XBHEA9aq/3cIRytzjXRxITUsiOIuRp6f8sOqoqduZw3U//tc5b+UgFPRPGMeQW0sLVqtONeFuIgUBKfV4COHLVL2Q0C9FlC8JMswBKn3zg4acUfCgE2ydRXbk9XBXfm4RLcyNasFVdlHQL46TEGtXTh8Pw9eyDBHFc7tSMof3J+VlDhtBpn/rTbgC+RrHDJ+9M+yfzAEE778EYd6aLGwXRp0hTXdzr+ud/CGsyBRl4UdHoycnkQ3HXP9RUZtZTcXpfqJZbsf/1tDMMPGal4vzWUqywz4XrHNBtuv6To82ug4HlYcjTsPXdAp3N7g1KDHF7lRATnDpHEE=
